name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: Sithi5/remote-ssh-commands-action@1.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          ssh-private-key: ${{ secrets.SSH_KEY }}
          script: "cd /home/ubuntu && ./deploy.sh"



